//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceLCShipment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLCShipment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceLCShipment", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Arrival Date.
        /// </summary>
        internal static string ArrivalDate {
            get {
                return ResourceManager.GetString("ArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assesment Value.
        /// </summary>
        internal static string AssesmentValue {
            get {
                return ResourceManager.GetString("AssesmentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Of Entry Date.
        /// </summary>
        internal static string BillOfEntryDate {
            get {
                return ResourceManager.GetString("BillOfEntryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Of Entry No.
        /// </summary>
        internal static string BillOfEntryNo {
            get {
                return ResourceManager.GetString("BillOfEntryNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Invoice.
        /// </summary>
        internal static string CommercialInvoice {
            get {
                return ResourceManager.GetString("CommercialInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        internal static string Container {
            get {
                return ResourceManager.GetString("Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty.
        /// </summary>
        internal static string Duty {
            get {
                return ResourceManager.GetString("Duty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Failed.
        /// </summary>
        internal static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill up all required data..
        /// </summary>
        internal static string FillRequiredData {
            get {
                return ResourceManager.GetString("FillRequiredData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LC Shipment &amp; Shipment Expences.
        /// </summary>
        internal static string Heading {
            get {
                return ResourceManager.GetString("Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCShipment Documents.
        /// </summary>
        internal static string LcShipmentDoc {
            get {
                return ResourceManager.GetString("LcShipmentDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Shipment found..
        /// </summary>
        internal static string NoShipment {
            get {
                return ResourceManager.GetString("NoShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Amount.
        /// </summary>
        internal static string PaidAmount {
            get {
                return ResourceManager.GetString("PaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payable Amount.
        /// </summary>
        internal static string PayableAmount {
            get {
                return ResourceManager.GetString("PayableAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Date.
        /// </summary>
        internal static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Release Date.
        /// </summary>
        internal static string PortReleaseDate {
            get {
                return ResourceManager.GetString("PortReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCShipment saved successfully!.
        /// </summary>
        internal static string SavedSuccess {
            get {
                return ResourceManager.GetString("SavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCShipment could not saved!.
        /// </summary>
        internal static string SavedUnSuccess {
            get {
                return ResourceManager.GetString("SavedUnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Date.
        /// </summary>
        internal static string ShipmentDate {
            get {
                return ResourceManager.GetString("ShipmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Number.
        /// </summary>
        internal static string ShipmentNumber {
            get {
                return ResourceManager.GetString("ShipmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LC Shipment &amp; Shipment Expences.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCShipment updated successfully!.
        /// </summary>
        internal static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCShipment could not updated!.
        /// </summary>
        internal static string UpdateUnSuccess {
            get {
                return ResourceManager.GetString("UpdateUnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel Description.
        /// </summary>
        internal static string VesselDescription {
            get {
                return ResourceManager.GetString("VesselDescription", resourceCulture);
            }
        }
    }
}
