//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFGSale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFGSale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceFGSale", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account #.
        /// </summary>
        internal static string AccountNo {
            get {
                return ResourceManager.GetString("AccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust. Amt..
        /// </summary>
        internal static string AdjustAmount {
            get {
                return ResourceManager.GetString("AdjustAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Name.
        /// </summary>
        internal static string AdjustmentName {
            get {
                return ResourceManager.GetString("AdjustmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Setup.
        /// </summary>
        internal static string AdjustmentSetup {
            get {
                return ResourceManager.GetString("AdjustmentSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount After Discount.
        /// </summary>
        internal static string AmountAfterDiscount {
            get {
                return ResourceManager.GetString("AmountAfterDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Mode.
        /// </summary>
        internal static string ApplyMode {
            get {
                return ResourceManager.GetString("ApplyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availabel Credit Limit.
        /// </summary>
        internal static string AvailabelCreditLimit {
            get {
                return ResourceManager.GetString("AvailabelCreditLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Exceed..
        /// </summary>
        internal static string BalanceExceed {
            get {
                return ResourceManager.GetString("BalanceExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        internal static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No. Required for every Online Payment..
        /// </summary>
        internal static string BankAccountRequ {
            get {
                return ResourceManager.GetString("BankAccountRequ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name Required for every CD/PDC Payment..
        /// </summary>
        internal static string BankReq {
            get {
                return ResourceManager.GetString("BankReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakage Period.
        /// </summary>
        internal static string BreakagePeriod {
            get {
                return ResourceManager.GetString("BreakagePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation On.
        /// </summary>
        internal static string CalculationOn {
            get {
                return ResourceManager.GetString("CalculationOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque #.
        /// </summary>
        internal static string Cheque {
            get {
                return ResourceManager.GetString("Cheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque No. Required for every CD/PDC Payment..
        /// </summary>
        internal static string ChequeReq {
            get {
                return ResourceManager.GetString("ChequeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission Periods.
        /// </summary>
        internal static string CommissionPeriod {
            get {
                return ResourceManager.GetString("CommissionPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        internal static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Phone.
        /// </summary>
        internal static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Delivery.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Type.
        /// </summary>
        internal static string CustomType {
            get {
                return ResourceManager.GetString("CustomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer.
        /// </summary>
        internal static string Dealer {
            get {
                return ResourceManager.GetString("Dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        internal static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Option.
        /// </summary>
        internal static string DeliverBy {
            get {
                return ResourceManager.GetString("DeliverBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Option must be Self Delivery..
        /// </summary>
        internal static string DeliveryByCustomerCheck {
            get {
                return ResourceManager.GetString("DeliveryByCustomerCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Site.
        /// </summary>
        internal static string DeliverySite {
            get {
                return ResourceManager.GetString("DeliverySite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery District.
        /// </summary>
        internal static string DeliveryZone {
            get {
                return ResourceManager.GetString("DeliveryZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Authorization.
        /// </summary>
        internal static string DiscountAuthorization {
            get {
                return ResourceManager.GetString("DiscountAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount amount is larger than total amount..
        /// </summary>
        internal static string DiscountOver {
            get {
                return ResourceManager.GetString("DiscountOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due/Advanced Adjustment.
        /// </summary>
        internal static string DueAdvancedAdjustment {
            get {
                return ResourceManager.GetString("DueAdvancedAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Item and Grade and Lot already Selected..
        /// </summary>
        internal static string DuplicateData {
            get {
                return ResourceManager.GetString("DuplicateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Good Sale Approve Failed.
        /// </summary>
        internal static string FGSaleApproveFailed {
            get {
                return ResourceManager.GetString("FGSaleApproveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Good Sale Approve Successfull!.
        /// </summary>
        internal static string FGSaleApproveSuccessful {
            get {
                return ResourceManager.GetString("FGSaleApproveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Good Sale Deleted Failed.
        /// </summary>
        internal static string FGSaleDeleteFailed {
            get {
                return ResourceManager.GetString("FGSaleDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Good Sale Deleted Successfully!.
        /// </summary>
        internal static string FGSaleDeleteSuccess {
            get {
                return ResourceManager.GetString("FGSaleDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Good Sale Review Failed.
        /// </summary>
        internal static string FGSaleReviewFailed {
            get {
                return ResourceManager.GetString("FGSaleReviewFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Good Sale Review Successfull!.
        /// </summary>
        internal static string FGSaleReviewSuccessful {
            get {
                return ResourceManager.GetString("FGSaleReviewSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Good Sale Saved Failed!.
        /// </summary>
        internal static string FGSaleSaveFailed {
            get {
                return ResourceManager.GetString("FGSaleSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Good Sale saved successfully!.
        /// </summary>
        internal static string FGSaleSaveSuccess {
            get {
                return ResourceManager.GetString("FGSaleSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Good Sale Update Failed!.
        /// </summary>
        internal static string FGSaleUpdateFailed {
            get {
                return ResourceManager.GetString("FGSaleUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Good Sale Update Successfully!.
        /// </summary>
        internal static string FGSaleUpdateSuccess {
            get {
                return ResourceManager.GetString("FGSaleUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        internal static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount File Required..
        /// </summary>
        internal static string FileReq {
            get {
                return ResourceManager.GetString("FileReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Of Cost.
        /// </summary>
        internal static string FreeOfCost {
            get {
                return ResourceManager.GetString("FreeOfCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        internal static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Required for all Sales Detail.
        /// </summary>
        internal static string GradeReq {
            get {
                return ResourceManager.GetString("GradeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Use.
        /// </summary>
        internal static string InternalUse {
            get {
                return ResourceManager.GetString("InternalUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        internal static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice List.
        /// </summary>
        internal static string InvoiceList {
            get {
                return ResourceManager.GetString("InvoiceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No.
        /// </summary>
        internal static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irregular.
        /// </summary>
        internal static string Irregular {
            get {
                return ResourceManager.GetString("Irregular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Required for all Sales Detail.
        /// </summary>
        internal static string ItemRequired {
            get {
                return ResourceManager.GetString("ItemRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount is larger than Unit price..
        /// </summary>
        internal static string LargeDiscount {
            get {
                return ResourceManager.GetString("LargeDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot.
        /// </summary>
        internal static string Lot {
            get {
                return ResourceManager.GetString("Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Required for all Sales Detail.
        /// </summary>
        internal static string LotReq {
            get {
                return ResourceManager.GetString("LotReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack Qty Required for all Sales Detail.
        /// </summary>
        internal static string PackQtyReq {
            get {
                return ResourceManager.GetString("PackQtyReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Quantity.
        /// </summary>
        internal static string PackQuantity {
            get {
                return ResourceManager.GetString("PackQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Date.
        /// </summary>
        internal static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Mode.
        /// </summary>
        internal static string PaymentMode {
            get {
                return ResourceManager.GetString("PaymentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        internal static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        internal static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        internal static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        internal static string Regular {
            get {
                return ResourceManager.GetString("Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Detail.
        /// </summary>
        internal static string SalesDetail {
            get {
                return ResourceManager.GetString("SalesDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Payment.
        /// </summary>
        internal static string SalesPayment {
            get {
                return ResourceManager.GetString("SalesPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Quantity.
        /// </summary>
        internal static string SalesQuantity {
            get {
                return ResourceManager.GetString("SalesQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        internal static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SN.
        /// </summary>
        internal static string SN {
            get {
                return ResourceManager.GetString("SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Discount.
        /// </summary>
        internal static string SpecialDiscount {
            get {
                return ResourceManager.GetString("SpecialDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Quantity.
        /// </summary>
        internal static string StockQuantity {
            get {
                return ResourceManager.GetString("StockQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Sale.
        /// </summary>
        internal static string TitleFGSale {
            get {
                return ResourceManager.GetString("TitleFGSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount :.
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Due/Advance Amount.
        /// </summary>
        internal static string TotalDueAdvanceAmount {
            get {
                return ResourceManager.GetString("TotalDueAdvanceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Payable.
        /// </summary>
        internal static string TotalPayable {
            get {
                return ResourceManager.GetString("TotalPayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Payable After Discount.
        /// </summary>
        internal static string TotalPayableAfterDiscount {
            get {
                return ResourceManager.GetString("TotalPayableAfterDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        internal static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price Discount.
        /// </summary>
        internal static string UnitPriceDiscount {
            get {
                return ResourceManager.GetString("UnitPriceDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit price of Sl#.
        /// </summary>
        internal static string UnitPriceReqPart1 {
            get {
                return ResourceManager.GetString("UnitPriceReqPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is zero.
        /// </summary>
        internal static string UnitPriceReqPart2 {
            get {
                return ResourceManager.GetString("UnitPriceReqPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Authorization.
        /// </summary>
        internal static string UpdateAuthorization {
            get {
                return ResourceManager.GetString("UpdateAuthorization", resourceCulture);
            }
        }
    }
}
