//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceItemDemand {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceItemDemand() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceItemDemand", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill up all Required Data..
        /// </summary>
        internal static string AllRequired {
            get {
                return ResourceManager.GetString("AllRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Failed. Demand already Issued..
        /// </summary>
        internal static string AlreadyIssued {
            get {
                return ResourceManager.GetString("AlreadyIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Failed.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand List.
        /// </summary>
        internal static string DemandList {
            get {
                return ResourceManager.GetString("DemandList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Category.
        /// </summary>
        internal static string ItemCat {
            get {
                return ResourceManager.GetString("ItemCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item required for all Demand details..
        /// </summary>
        internal static string ItemRequired {
            get {
                return ResourceManager.GetString("ItemRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Demand List.
        /// </summary>
        internal static string LblAllItemDemandList {
            get {
                return ResourceManager.GetString("LblAllItemDemandList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        internal static string LblApprovedBy {
            get {
                return ResourceManager.GetString("LblApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved On.
        /// </summary>
        internal static string LblApprovedOn {
            get {
                return ResourceManager.GetString("LblApprovedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demanded By.
        /// </summary>
        internal static string LblDemandedBy {
            get {
                return ResourceManager.GetString("LblDemandedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason of Demand .
        /// </summary>
        internal static string LblDemandFor {
            get {
                return ResourceManager.GetString("LblDemandFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand No..
        /// </summary>
        internal static string LblDemandNo {
            get {
                return ResourceManager.GetString("LblDemandNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand On.
        /// </summary>
        internal static string LblDemandOn {
            get {
                return ResourceManager.GetString("LblDemandOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string LblDemandUsage {
            get {
                return ResourceManager.GetString("LblDemandUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Code.
        /// </summary>
        internal static string LblDepartmentCode {
            get {
                return ResourceManager.GetString("LblDepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Demand.
        /// </summary>
        internal static string LblItemDemand {
            get {
                return ResourceManager.GetString("LblItemDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Demand Detail.
        /// </summary>
        internal static string LblItemDemandDetail {
            get {
                return ResourceManager.GetString("LblItemDemandDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Code.
        /// </summary>
        internal static string LblLocationCode {
            get {
                return ResourceManager.GetString("LblLocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item demand found.
        /// </summary>
        internal static string LblNoItemDemandFound {
            get {
                return ResourceManager.GetString("LblNoItemDemandFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part No..
        /// </summary>
        internal static string LblPartNo {
            get {
                return ResourceManager.GetString("LblPartNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Item Demand List.
        /// </summary>
        internal static string LblPendingItemDemandList {
            get {
                return ResourceManager.GetString("LblPendingItemDemandList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string LblPriority {
            get {
                return ResourceManager.GetString("LblPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty. Requested.
        /// </summary>
        internal static string LblQuantityRequested {
            get {
                return ResourceManager.GetString("LblQuantityRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string LblStatus {
            get {
                return ResourceManager.GetString("LblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total item demand.
        /// </summary>
        internal static string LblTotalItemDemand {
            get {
                return ResourceManager.GetString("LblTotalItemDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string LblUnitOfMeasurement {
            get {
                return ResourceManager.GetString("LblUnitOfMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order No..
        /// </summary>
        internal static string LblWorkOrderNo {
            get {
                return ResourceManager.GetString("LblWorkOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Demand Detail not found..
        /// </summary>
        internal static string MsgItemDemandDetailNotFound {
            get {
                return ResourceManager.GetString("MsgItemDemandDetailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Demand Details..
        /// </summary>
        internal static string NeedDemandDetails {
            get {
                return ResourceManager.GetString("NeedDemandDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity required for all Demand details..
        /// </summary>
        internal static string QtyRequired {
            get {
                return ResourceManager.GetString("QtyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
    }
}
