//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceAutoGeneratedNo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceAutoGeneratedNo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceAutoGeneratedNo", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daily.
        /// </summary>
        internal static string daily {
            get {
                return ResourceManager.GetString("daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.
        /// </summary>
        internal static string dd {
            get {
                return ResourceManager.GetString("dd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand.
        /// </summary>
        internal static string Demand {
            get {
                return ResourceManager.GetString("Demand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        internal static string Issue {
            get {
                return ResourceManager.GetString("Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Index.
        /// </summary>
        internal static string LastIndex {
            get {
                return ResourceManager.GetString("LastIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastIndexDate.
        /// </summary>
        internal static string LastIndexDate {
            get {
                return ResourceManager.GetString("LastIndexDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Generated Number.
        /// </summary>
        internal static string LblAutoGeneratedNo {
            get {
                return ResourceManager.GetString("LblAutoGeneratedNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No AutoGenerated Number  Found.
        /// </summary>
        internal static string LblNoAutoGeneratedNoFound {
            get {
                return ResourceManager.GetString("LblNoAutoGeneratedNoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Auto Generated Number.
        /// </summary>
        internal static string LblTotalAutoGeneratedNo {
            get {
                return ResourceManager.GetString("LblTotalAutoGeneratedNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM.
        /// </summary>
        internal static string MM {
            get {
                return ResourceManager.GetString("MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monthly.
        /// </summary>
        internal static string monthly {
            get {
                return ResourceManager.GetString("monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Generated No deleted successfully!.
        /// </summary>
        internal static string msg_del {
            get {
                return ResourceManager.GetString("msg_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Generated can&apos;t be deleted!.
        /// </summary>
        internal static string msg_not_del {
            get {
                return ResourceManager.GetString("msg_not_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PeriodFormat.
        /// </summary>
        internal static string PeriodFormat {
            get {
                return ResourceManager.GetString("PeriodFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefreshFrequency.
        /// </summary>
        internal static string RefreshFrequency {
            get {
                return ResourceManager.GetString("RefreshFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisition.
        /// </summary>
        internal static string Requisition {
            get {
                return ResourceManager.GetString("Requisition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string ResourceAutoGeneratedNoList {
            get {
                return ResourceManager.GetString("ResourceAutoGeneratedNoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesInvoiceNo.
        /// </summary>
        internal static string SalesInvoiceNo {
            get {
                return ResourceManager.GetString("SalesInvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator1.
        /// </summary>
        internal static string Separator1 {
            get {
                return ResourceManager.GetString("Separator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator2.
        /// </summary>
        internal static string Separator2 {
            get {
                return ResourceManager.GetString("Separator2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Index.
        /// </summary>
        internal static string StartIndex {
            get {
                return ResourceManager.GetString("StartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialigation For.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialigation For.
        /// </summary>
        internal static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yearly.
        /// </summary>
        internal static string yearly {
            get {
                return ResourceManager.GetString("yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy.
        /// </summary>
        internal static string yyyy {
            get {
                return ResourceManager.GetString("yyyy", resourceCulture);
            }
        }
    }
}
